_BASE_: "../../Base-RetinaNet.yaml"

MODEL:
    META_ARCHITECTURE: "ProbabilisticRetinaNet"

    WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

    RESNETS:
      DEPTH: 50

    RETINANET:
        NUM_CLASSES: 20

DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory

#SOLVER:
#    IMS_PER_BATCH: 4
#    BASE_LR: 0.0025  # Note that RetinaNet uses a different default learning rate
#    STEPS: (60000, 80000)
#    MAX_ITER: 90000

SOLVER:
    IMS_PER_BATCH: 4
    STEPS: (12000, 16000)
    MAX_ITER: 18000  # 17.4 epochs
    WARMUP_ITERS: 100

INPUT:
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
    MIN_SIZE_TEST: 800

DATASETS:
  #TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
    TRAIN: ("voc_2012_trainval",)
    TEST: ("voc_2012_test",)

VERSION: 2
