_BASE_: "Base-VOC-RetinaNet.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        DROPOUT_RATE: 0.2 # 0.0 for no dropout

        # One of the following Loss types: loss_attenuation'.
        CLS_VAR_LOSS:
            NAME: 'loss_attenuation'
            NUM_SAMPLES: 10

        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        BBOX_COV_LOSS:
            NAME: 'negative_log_likelihood'
            COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal' # Settings for dropout


ACTIVE_LEARNING:
    # starting number of randomly labeled images in the training set
    START_N: 3000
    # number of images, that will be labeled per active learning step
    STEP_N: 500
    # active learning training epoch per step
    # used to calculate the max iter for the detectron training step
    EPOCH: 10

    # type of cls score for each detection in one image
    # "max_conf", "entropy"
    DET_CLS_SCORE: "entropy"

    # type of merging strategy for the multiple cls score per detection in one image
    # summarizes the detection cls scores in the image
    # "mean", "max"
    DET_CLS_MERGE_MODE: "mean"

    # type of box scoring and merging will be added soon

    # weight of the cls score and box score of the image
    W_CLS_SCORE: 0.5

    OUT_DIR: "outputs/VOC_10_steps"